"""encrypt_credentials_schema

Revision ID: 046b9b0bfc25
Revises: cc18662bb34f
Create Date: 2026-02-05 15:42:08.704698

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '046b9b0bfc25'
down_revision: Union[str, Sequence[str], None] = '3a6c5d4e2f1b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    inspector = sa.inspect(bind)
    cols = [c['name'] for c in inspector.get_columns('credential')]

    with op.batch_alter_table('credential', schema=None) as batch_op:
        if 'encrypted_password' not in cols:
            batch_op.add_column(sa.Column('encrypted_password', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
        if 'encrypted_enable_password' not in cols:
            batch_op.add_column(sa.Column('encrypted_enable_password', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    
    # Data migration: Copy existing encrypted data to new columns
    # Only if source columns exist
    has_password = 'password' in cols
    has_enable_password = 'enable_password' in cols

    if has_password:
        op.execute("UPDATE credential SET encrypted_password = password")
    if has_enable_password:
        op.execute("UPDATE credential SET encrypted_enable_password = enable_password")

    with op.batch_alter_table('credential', schema=None) as batch_op:
        if has_enable_password:
            batch_op.drop_column('enable_password')
        if has_password:
            batch_op.drop_column('password')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('credential', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password', sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column('enable_password', sa.VARCHAR(), nullable=True))
        batch_op.drop_column('encrypted_enable_password')
        batch_op.drop_column('encrypted_password')

    # ### end Alembic commands ###
