"""add webshell record

Revision ID: db196fc6e6a8
Revises: p4q5r6s7t8u9
Create Date: 2026-04-09 11:05:45.077843

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'db196fc6e6a8'
down_revision: Union[str, Sequence[str], None] = 'p4q5r6s7t8u9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    inspector = sa.inspect(bind)
    existing_tables = inspector.get_table_names()
    if "backuprecord" in existing_tables:
        index_names = (
            "ix_backuprecord_config_text_trgm",
            "ix_backuprecord_config_text_trgm_gin",
            "ix_backuprecord_config_text_tsv",
            "ix_backuprecord_config_text_tsv_gin",
            "ix_backuprecord_success_device_started_at",
        )
        if bind.dialect.name == "postgresql":
            for index_name in index_names:
                op.execute(f"DROP INDEX IF EXISTS {index_name}")
        else:
            existing_indexes = {idx["name"] for idx in inspector.get_indexes("backuprecord")}
            for index_name in index_names:
                if index_name in existing_indexes:
                    op.drop_index(index_name, table_name="backuprecord")

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('mfa_enabled',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
        batch_op.alter_column('recovery_codes_hashed',
               existing_type=sa.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('recovery_codes_hashed',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('mfa_enabled',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))

    with op.batch_alter_table('backuprecord', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_backuprecord_success_device_started_at'), ['device_id', sa.literal_column('started_at DESC')], unique=False, postgresql_where='(success = true)')
        batch_op.create_index(batch_op.f('ix_backuprecord_config_text_tsv_gin'), [sa.literal_column("to_tsvector('simple'::regconfig, COALESCE(config_text, ''::character varying)::text)")], unique=False, postgresql_using='gin')
        batch_op.create_index(batch_op.f('ix_backuprecord_config_text_tsv'), [sa.literal_column("to_tsvector('simple'::regconfig, COALESCE(config_text, ''::character varying)::text)")], unique=False, postgresql_using='gin', postgresql_where='(success IS TRUE)')
        batch_op.create_index(batch_op.f('ix_backuprecord_config_text_trgm_gin'), ['config_text'], unique=False, postgresql_ops={'config_text': 'gin_trgm_ops'}, postgresql_using='gin')
        batch_op.create_index(batch_op.f('ix_backuprecord_config_text_trgm'), ['config_text'], unique=False, postgresql_ops={'config_text': 'gin_trgm_ops'}, postgresql_using='gin', postgresql_where='(success IS TRUE)')

    # ### end Alembic commands ###
