"""add config_snapshot_hash to backuprecord

Revision ID: f8dbd5098d13
Revises: 0001_baseline
Create Date: 2026-02-03 12:44:00.230862

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'f8dbd5098d13'
down_revision: Union[str, Sequence[str], None] = '0002_legacy_schema'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Helper to drop table and indexes safely
    bind = op.get_bind()
    inspector = sa.inspect(bind)
    existing_tables = inspector.get_table_names()

    def drop_table_safe(table_name, indexes=None):
        if table_name in existing_tables:
            if indexes:
                existing_indexes = [i['name'] for i in inspector.get_indexes(table_name)]
                for idx in indexes:
                    if idx in existing_indexes:
                        op.drop_index(op.f(idx), table_name=table_name)
            op.drop_table(table_name)

    def drop_column_safe(batch_op, column_name, table_name):
        if table_name in existing_tables:
            columns = [c['name'] for c in inspector.get_columns(table_name)]
            if column_name in columns:
                batch_op.drop_column(column_name)

    def add_column_safe(batch_op, column, table_name):
        if table_name in existing_tables:
            column_name = column.name
            columns = [c['name'] for c in inspector.get_columns(table_name)]
            if column_name not in columns:
                batch_op.add_column(column)

    # Cleanup potential temp tables from failed batch migrations
    drop_table_safe('_alembic_tmp_auditlog')
    drop_table_safe('_alembic_tmp_backuprecord')
    drop_table_safe('_alembic_tmp_credential')
    drop_table_safe('_alembic_tmp_device')
    drop_table_safe('_alembic_tmp_loginlog')
    drop_table_safe('_alembic_tmp_user')

    drop_table_safe('diffrule', ['ix_diffrule_created_at', 'ix_diffrule_group_id', 'ix_diffrule_platform', 'ix_diffrule_updated_at'])
    drop_table_safe('configtemplate', ['ix_configtemplate_name'])
    drop_table_safe('diffignorerule', ['ix_diffignorerule_created_at', 'ix_diffignorerule_group_id', 'ix_diffignorerule_platform'])
    drop_table_safe('systemsetting')
    drop_table_safe('loginlog_old', ['ix_loginlog_created_at', 'ix_loginlog_username'])
    drop_table_safe('group', ['ix_group_name'])

    with op.batch_alter_table('auditlog', schema=None) as batch_op:
        drop_column_safe(batch_op, 'user_agent', 'auditlog')
        drop_column_safe(batch_op, 'target_device_id', 'auditlog')
        drop_column_safe(batch_op, 'run_id', 'auditlog')
        drop_column_safe(batch_op, 'path', 'auditlog')

    with op.batch_alter_table('backuprecord', schema=None) as batch_op:
        add_column_safe(batch_op, sa.Column('config_snapshot_hash', sqlmodel.sql.sqltypes.AutoString(), nullable=True), 'backuprecord')
        batch_op.alter_column('duration_seconds',
                   existing_type=sa.REAL(),
                   type_=sa.Float(),
                   existing_nullable=True)
        batch_op.alter_column('failure_type',
                   existing_type=sa.TEXT(),
                   type_=sqlmodel.sql.sqltypes.AutoString(),
                   existing_nullable=True)

    with op.batch_alter_table('credential', schema=None) as batch_op:
        batch_op.alter_column('remarks',
                   existing_type=sa.TEXT(),
                   type_=sqlmodel.sql.sqltypes.AutoString(),
                   existing_nullable=True)

    # Drop indexes that depend on columns being dropped or are being removed BEFORE batch
    if 'device' in existing_tables:
        indexes = [i['name'] for i in inspector.get_indexes('device')]
        if 'ix_device_status' in indexes:
             op.drop_index(op.f('ix_device_status'), table_name='device')

    with op.batch_alter_table('device', schema=None) as batch_op:
        batch_op.alter_column('id',
                   existing_type=sa.INTEGER(),
                   nullable=False,
                   autoincrement=True)
        batch_op.alter_column('name',
                   existing_type=sa.TEXT(),
                   type_=sqlmodel.sql.sqltypes.AutoString(),
                   existing_nullable=False)
        batch_op.alter_column('host',
                   existing_type=sa.TEXT(),
                   type_=sqlmodel.sql.sqltypes.AutoString(),
                   existing_nullable=False)
        batch_op.alter_column('login_method',
                   existing_type=sa.TEXT(),
                   type_=sqlmodel.sql.sqltypes.AutoString(),
                   nullable=False,
                   existing_server_default=sa.text("'ssh'"))
        batch_op.alter_column('platform',
                   existing_type=sa.TEXT(),
                   type_=sqlmodel.sql.sqltypes.AutoString(),
                   existing_nullable=False)
        batch_op.alter_column('reachability_error',
                   existing_type=sa.TEXT(),
                   type_=sqlmodel.sql.sqltypes.AutoString(),
                   existing_nullable=True)
        drop_column_safe(batch_op, 'username', 'device')
        drop_column_safe(batch_op, 'reach_success', 'device')
        drop_column_safe(batch_op, 'password', 'device')
        drop_column_safe(batch_op, 'status', 'device')
        drop_column_safe(batch_op, 'reach_error', 'device')
        drop_column_safe(batch_op, 'reach_duration', 'device')
        drop_column_safe(batch_op, 'reach_last_checked', 'device')
        drop_column_safe(batch_op, 'ssh_key_path', 'device')
        drop_column_safe(batch_op, 'enable_password', 'device')

    # Create new indexes for device
    if 'device' in existing_tables:
        indexes = [i['name'] for i in inspector.get_indexes('device')]
        if 'ix_device_default_template_id' not in indexes:
             op.create_index(op.f('ix_device_default_template_id'), 'device', ['default_template_id'], unique=False)

    with op.batch_alter_table('loginlog', schema=None) as batch_op:
        batch_op.alter_column('id',
                   existing_type=sa.INTEGER(),
                   nullable=False,
                   autoincrement=True)
        batch_op.alter_column('created_at',
                   existing_type=sa.DATETIME(),
                   nullable=False)

    # Indices for loginlog
    if 'loginlog' in existing_tables:
        indexes = [i['name'] for i in inspector.get_indexes('loginlog')]
        if 'ix_loginlog_created_at' not in indexes:
            op.create_index(op.f('ix_loginlog_created_at'), 'loginlog', ['created_at'], unique=False)
        if 'ix_loginlog_username' not in indexes:
            op.create_index(op.f('ix_loginlog_username'), 'loginlog', ['username'], unique=False)

    # Drop indexes for user before batch
    if 'user' in existing_tables:
        indexes = [i['name'] for i in inspector.get_indexes('user')]
        if 'ix_user_email' in indexes:
            op.drop_index(op.f('ix_user_email'), table_name='user')

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('group_access_type',
                   existing_type=sa.VARCHAR(),
                   nullable=False,
                   existing_server_default=sa.text("'all'"))
        batch_op.alter_column('password_expired',
                   existing_type=sa.BOOLEAN(),
                   nullable=False,
                   existing_server_default=sa.text('0'))

    # Create new indexes for user
    if 'user' in existing_tables:
        indexes = [i['name'] for i in inspector.get_indexes('user')]
        if 'ix_user_username' not in indexes:
            op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.create_index(op.f('ix_user_email'), 'user', ['username'], unique=False)
    op.alter_column('user', 'password_expired',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('user', 'group_access_type',
               existing_type=sa.VARCHAR(),
               nullable=True,
               existing_server_default=sa.text("'all'"))
    op.drop_index(op.f('ix_loginlog_username'), table_name='loginlog')
    op.drop_index(op.f('ix_loginlog_created_at'), table_name='loginlog')
    op.alter_column('loginlog', 'created_at',
               existing_type=sa.DATETIME(),
               nullable=True)
    op.alter_column('loginlog', 'id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)
    op.add_column('device', sa.Column('enable_password', sa.TEXT(), nullable=True))
    op.add_column('device', sa.Column('ssh_key_path', sa.TEXT(), nullable=True))
    op.add_column('device', sa.Column('reach_last_checked', sa.DATETIME(), nullable=True))
    op.add_column('device', sa.Column('reach_duration', sa.INTEGER(), nullable=True))
    op.add_column('device', sa.Column('reach_error', sa.TEXT(), nullable=True))
    op.add_column('device', sa.Column('status', sa.VARCHAR(), server_default=sa.text("'active'"), nullable=True))
    op.add_column('device', sa.Column('password', sa.TEXT(), nullable=True))
    op.add_column('device', sa.Column('reach_success', sa.BOOLEAN(), nullable=True))
    op.add_column('device', sa.Column('username', sa.TEXT(), nullable=True))
    op.drop_index(op.f('ix_device_default_template_id'), table_name='device')
    op.create_index(op.f('ix_device_status'), 'device', ['status'], unique=False)
    op.alter_column('device', 'reachability_error',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('device', 'platform',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('device', 'login_method',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TEXT(),
               nullable=True,
               existing_server_default=sa.text("'ssh'"))
    op.alter_column('device', 'host',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('device', 'name',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('device', 'id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)
    op.alter_column('credential', 'remarks',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('backuprecord', 'failure_type',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('backuprecord', 'duration_seconds',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=True)
    op.drop_column('backuprecord', 'config_snapshot_hash')
    op.add_column('auditlog', sa.Column('path', sa.TEXT(), nullable=True))
    op.add_column('auditlog', sa.Column('run_id', sa.CHAR(length=36), nullable=True))
    op.add_column('auditlog', sa.Column('target_device_id', sa.INTEGER(), nullable=True))
    op.add_column('auditlog', sa.Column('user_agent', sa.TEXT(), nullable=True))
    op.create_table('group',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(), nullable=False),
    sa.Column('description', sa.VARCHAR(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_group_name'), 'group', ['name'], unique=1)
    op.create_table('loginlog_old',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('username', sa.VARCHAR(), nullable=False),
    sa.Column('ip_address', sa.VARCHAR(), nullable=True),
    sa.Column('user_agent', sa.VARCHAR(), nullable=True),
    sa.Column('status', sa.BOOLEAN(), nullable=False),
    sa.Column('fail_reason', sa.VARCHAR(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_loginlog_username'), 'loginlog_old', ['username'], unique=False)
    op.create_index(op.f('ix_loginlog_created_at'), 'loginlog_old', ['created_at'], unique=False)
    op.create_table('systemsetting',
    sa.Column('key', sa.VARCHAR(), nullable=False),
    sa.Column('value', sa.VARCHAR(), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('diffignorerule',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(), nullable=False),
    sa.Column('pattern', sa.VARCHAR(), nullable=False),
    sa.Column('platform', sa.VARCHAR(), nullable=True),
    sa.Column('group_id', sa.INTEGER(), nullable=True),
    sa.Column('description', sa.VARCHAR(), nullable=True),
    sa.Column('enabled', sa.BOOLEAN(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_diffignorerule_platform'), 'diffignorerule', ['platform'], unique=False)
    op.create_index(op.f('ix_diffignorerule_group_id'), 'diffignorerule', ['group_id'], unique=False)
    op.create_index(op.f('ix_diffignorerule_created_at'), 'diffignorerule', ['created_at'], unique=False)
    op.create_table('configtemplate',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(), nullable=False),
    sa.Column('content', sa.VARCHAR(), nullable=False),
    sa.Column('platform', sa.VARCHAR(), nullable=False),
    sa.Column('description', sa.VARCHAR(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_configtemplate_name'), 'configtemplate', ['name'], unique=1)
    op.create_table('diffrule',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(), nullable=False),
    sa.Column('pattern', sa.VARCHAR(), nullable=False),
    sa.Column('platform', sa.VARCHAR(), nullable=True),
    sa.Column('group_id', sa.INTEGER(), nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_diffrule_updated_at'), 'diffrule', ['updated_at'], unique=False)
    op.create_index(op.f('ix_diffrule_platform'), 'diffrule', ['platform'], unique=False)
    op.create_index(op.f('ix_diffrule_group_id'), 'diffrule', ['group_id'], unique=False)
    op.create_index(op.f('ix_diffrule_created_at'), 'diffrule', ['created_at'], unique=False)
    # ### end Alembic commands ###
